// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl3ujm0zN5knPKCIk-aS5QvksIvej_WAc',
    appId: '1:135514481989:web:60cc5bfc3e9df630e58a2c',
    messagingSenderId: '135514481989',
    projectId: 'devathon-saylani',
    authDomain: 'devathon-saylani.firebaseapp.com',
    storageBucket: 'devathon-saylani.appspot.com',
    measurementId: 'G-PG6YV087D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-AW6y-adVOPyXcX4SzVBXHjrCl8a_KMo',
    appId: '1:135514481989:android:1b74ed74cc6179e4e58a2c',
    messagingSenderId: '135514481989',
    projectId: 'devathon-saylani',
    storageBucket: 'devathon-saylani.appspot.com',
  );
}
